### ISSUE TITLE
Fetching citations fails

### ISSUE THREAD

**Issue by achourasia** [scotteuser/open_citations#1]
When the trigger is used to update citations via the UI for a single publication or all publications or via drush it completes instantaneously. However, no citations are added to any publications. 

Setup: Install module, generate 50 publications using the devel generate option.

The following logs are added to Drupal log
Error: Call to undefined method Drupal\open_citations\Commands\CitationsUpdateDrushCommand::t() in Drupal\open_citations\Commands\CitationsUpdateDrushCommand->updateCitations() (line 25 of /opt/drupal/web/modules/custom/open_citations/src/Commands/CitationsUpdateDrushCommand.php)

This issue can be temporarily avoided by removing the t() function. Running the update citation trigger again logs the following warning.

Warning: Undefined array key 50 in Drupal\open_citations\OpenCitationsBatches::operationCallback() (line 136 of /opt/drupal/web/modules/custom/open_citations/src/OpenCitationsBatches.php) 

Seems like the batch processing is not be triggered.

PS: Great talk and module at Drupal Dev Days. Thanks for sharing.

**Comment by achourasia** [comment]
Nevermind the module works as expected. 
I had to update drupal from 9.2.12 to latest (9.4.6). Earlier, instead of using composer I used git clone which obviously did not catch the Drupal version requirement early on.

**Comment by scotteuser** [comment]
Cool glad that worked out in the end 🙂
