### ISSUE TITLE
Is there a limit, with max citations = 3?

### ISSUE THREAD

**Issue by achourasia** [scotteuser/open_citations#2]
Is there a limit imposed to fetch a maximum of three citations for any publications? On repeated triggers via UI or drush no new citations are added to the publications.

For example, open citations own example with DOI [10.1186/1756-8722-6-59](http://opencitations.net/index/search?text=10.1186%2F1756-8722-6-59&rule=citingdoi) has 66 citations, but the module only fetches the following three 

10.1016/j.biopha.2017.01.070Receptor Tyrosine Kinase-Like Orphan Receptor 1 (Ror-1): An Emerging Target For Diagnosis And Therapy Of Chronic Lymphocytic Leukemia
10.1016/j.bmcl.2015.01.032Potent And Selective Bruton’S Tyrosine Kinase Inhibitors: Discovery Of Gdc-0834
10.1016/j.bmc.2019.06.023Discovery And Biological Evaluation Of Pyrimido[4,5-D]Pyrimidine-2,4(1H,3H)-Dione Derivatives As Potent Bruton’S Tyrosine Kinase Inhibitors

**Comment by scotteuser** [comment]
Yep it's https://github.com/scotteuser/open_citations/blob/main/src/OpenCitationsClient.php#L70 there is an arbitrary limit applied to be kind to their API when demoing it. Similarly you'll find a sleep() higher up in the same file with a similar comment.

**Comment by achourasia** [comment]
Great thanks for pointing out max and sleep lines. I grep'ed for max in the code, but missed out that line.
